#!/bin/bash

set -eu
THISDIR="$(cd $(dirname "${BASH_SOURCE[0]}") && pwd -P)"
source $THISDIR/common.sh

if ! virt_domain_exists $NODE; then
    exit 0
fi

node_address=$(virt_domain_ip_address $NODE)

if [ -n "$node_address" ]; then
    system_id=$(maas_system_id $MAAS_PROFILE $node_address)
    if [ -n "$system_id" ]; then
	maas $MAAS_PROFILE node delete $system_id
    fi
fi
