#!/bin/bash

set -u
THISDIR="$(cd $(dirname "${BASH_SOURCE[0]}") && pwd -P)"
source $THISDIR/common.sh

vol_path=$(virt_domain_volume_path $VIRT_POOL $NODE)

[ -n "$vol_path" ] && die "volume already exists"
    
virsh vol-create-as $VIRT_POOL $NODE --format $VIRT_IMAGE_TYPE --capacity ${KVM_DISK_SIZE:-12G}
