#!/bin/bash

set -u
THISDIR="$(cd $(dirname "${BASH_SOURCE[0]}") && pwd -P)"
source $THISDIR/common.sh

node_state=$(virsh domstate $NODE)

if [ "$node_state" != "shut off" ]; then
    die "node $NODE must be shut off; currently in state '$node_state'"
fi

set +e

pxe_network_addr=$(virt_network_address ${NETWORKS[0]})

if [ -z "$pxe_network_addr" ]; then
    die "could not determine IP address for PXE network ${NETWORKS[0]}'"
fi

system_id=$(maas_system_id $MAAS_PROFILE $(virt_domain_ip_address $NODE))

if [ -z "$system_id" ]; then
    die "could not determine system_id for $NODE in $MAAS_PROFILE"
fi

set -e

maas_version=$(maas_version $MAAS_PROFILE)

if [ "$maas_version" = "1" ]; then
    power="node"
    accept="nodes"
else
    power="machine"
    accept="machines"
fi

maas $MAAS_PROFILE $power update $system_id \
     power_type=virsh \
     power_parameters_power_address=qemu+ssh://$USER@$pxe_network_addr/system \
     power_parameters_power_id=$NODE \
     hostname=$NODE

if [ -n "$TAGS" ]; then
    for t in $(echo "$TAGS" | tr ',' '\n'); do
	maas $MAAS_PROFILE tags new name="$t" || true
	maas $MAAS_PROFILE tag update-nodes "$t" add=$system_id || true
    done
fi

maas $MAAS_PROFILE $accept accept $accept=$system_id
