#!/bin/bash

set -eu
THISDIR="$(cd $(dirname "${BASH_SOURCE[0]}") && pwd -P)"
source $THISDIR/common.sh

if virt_domain_exists $NODE; then
    die "domain $NODE already exists"
fi

networks_args=""
for net in ${NETWORKS[@]}; do
    networks_args+="--network=network=$net,model=virtio"
done

virt-install \
    --name=$NODE \
    --connect=${QEMU_URI} \
    --ram=$VIRT_RAM \
    --vcpus=$VIRT_CPUS \
    --hvm \
    --virt-type=kvm \
    --boot network,hd \
    --graphics vnc \
    --noautoconsole \
    --os-type=linux \
    --os-variant=generic \
    --accelerate \
    --disk=$VIRT_IMAGE_DIR/${NODE}.${VIRT_IMAGE_TYPE},bus=virtio,format=${VIRT_IMAGE_TYPE},cache=writeback,sparse=true,size=${VIRT_DISK_SIZE} \
    $networks_args

